# theme: minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "0ld Camel's blog on yml"
author: Bao Dai
description: the story of a fat cat and a skinny cat
